"""NVIDIA Shield profiles."""

SHIELD_IR = DeviceProfile(
    id="shield_ir",
    name="NVIDIA Shield (IR)",
    brand="NVIDIA",
    category="streamer",
    model_years="2017+",
    description="NVIDIA Shield TV IR receiver.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("nvidia", ""),
    ir_codes={
        "power": nec(0x72, 0x00, "power"),
        "home": nec(0x72, 0x01, "home"),
        "back": nec(0x72, 0x02, "back"),
        "up": nec(0x72, 0x03, "up"),
        "down": nec(0x72, 0x04, "down"),
        "left": nec(0x72, 0x05, "left"),
        "right": nec(0x72, 0x06, "right"),
        "ok": nec(0x72, 0x07, "ok"),
        "vol_up": nec(0x72, 0x08, "vol_up"),
        "vol_down": nec(0x72, 0x09, "vol_down"),
        "mute": nec(0x72, 0x0A, "mute"),
        "play": nec(0x72, 0x10, "play"),
        "pause": nec(0x72, 0x11, "pause"),
        "rewind": nec(0x72, 0x12, "rewind"),
        "fast_forward": nec(0x72, 0x13, "fast_forward"),
    },
)
register_profile(SHIELD_IR)

SHIELD_ADB = DeviceProfile(
    id="shield_adb",
    name="NVIDIA Shield (ADB Network)",
    brand="NVIDIA",
    category="streamer",
    model_years="2017+",
    description="NVIDIA Shield Android TV control via ADB.",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("nvidia", ""),
    network_port=5555,
    network_protocol="adb",
    network_commands={
        "home": NetworkCommand("home", "ADB", "input keyevent 3", {}),
        "back": NetworkCommand("back", "ADB", "input keyevent 4", {}),
        "up": NetworkCommand("up", "ADB", "input keyevent 19", {}),
        "down": NetworkCommand("down", "ADB", "input keyevent 20", {}),
        "left": NetworkCommand("left", "ADB", "input keyevent 21", {}),
        "right": NetworkCommand("right", "ADB", "input keyevent 22", {}),
        "select": NetworkCommand("select", "ADB", "input keyevent 23", {}),
        "play_pause": NetworkCommand("play_pause", "ADB", "input keyevent 85", {}),
        "play": NetworkCommand("play", "ADB", "input keyevent 126", {}),
        "pause": NetworkCommand("pause", "ADB", "input keyevent 127", {}),
        "vol_up": NetworkCommand("vol_up", "ADB", "input keyevent 24", {}),
        "vol_down": NetworkCommand("vol_down", "ADB", "input keyevent 25", {}),
        "mute": NetworkCommand("mute", "ADB", "input keyevent 164", {}),
        "sleep": NetworkCommand("sleep", "ADB", "input keyevent 223", {}),
        "wake": NetworkCommand("wake", "ADB", "input keyevent 224", {}),
        "launch_netflix": NetworkCommand("launch_netflix", "ADB", 
            "am start -n com.netflix.ninja/.MainActivity", {}),
        "launch_youtube": NetworkCommand("launch_youtube", "ADB",
            "am start -n com.google.android.youtube.tv/com.google.android.apps.youtube.tv.activity.ShellActivity", {}),
        "launch_plex": NetworkCommand("launch_plex", "ADB",
            "am start -n com.plexapp.android/.MainActivity", {}),
        "launch_geforce_now": NetworkCommand("launch_geforce_now", "ADB",
            "am start -n com.nvidia.geforcenow/.MainActivity", {}),
    },
)
register_profile(SHIELD_ADB)
