"""DirecTV profiles."""

DIRECTV_IR = DeviceProfile(
    id="directv_ir",
    name="DirecTV (IR)",
    brand="DirecTV",
    category="cable",
    model_years="2012+",
    description="DirecTV receivers and Genie DVRs.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("directv", ""),
    ir_codes={
        "power": nec(0x16, 0x50, "power"),
        "power_on": nec(0x16, 0x51, "power_on"),
        "power_off": nec(0x16, 0x52, "power_off"),
        "guide": nec(0x16, 0x4E, "guide"),
        "menu": nec(0x16, 0x4F, "menu"),
        "list": nec(0x16, 0x53, "list"),
        "exit": nec(0x16, 0x54, "exit"),
        "info": nec(0x16, 0x55, "info"),
        "up": nec(0x16, 0x56, "up"),
        "down": nec(0x16, 0x57, "down"),
        "left": nec(0x16, 0x58, "left"),
        "right": nec(0x16, 0x59, "right"),
        "select": nec(0x16, 0x5A, "select"),
        "back": nec(0x16, 0x5B, "back"),
        "ch_up": nec(0x16, 0x5C, "ch_up"),
        "ch_down": nec(0x16, 0x5D, "ch_down"),
        "prev": nec(0x16, 0x5E, "prev"),
        "play": nec(0x16, 0x60, "play"),
        "pause": nec(0x16, 0x61, "pause"),
        "stop": nec(0x16, 0x62, "stop"),
        "record": nec(0x16, 0x63, "record"),
        "rewind": nec(0x16, 0x64, "rewind"),
        "fast_forward": nec(0x16, 0x65, "fast_forward"),
        "replay": nec(0x16, 0x66, "replay"),
        "advance": nec(0x16, 0x67, "advance"),
        "0": nec(0x16, 0x00, "0"),
        "1": nec(0x16, 0x01, "1"),
        "2": nec(0x16, 0x02, "2"),
        "3": nec(0x16, 0x03, "3"),
        "4": nec(0x16, 0x04, "4"),
        "5": nec(0x16, 0x05, "5"),
        "6": nec(0x16, 0x06, "6"),
        "7": nec(0x16, 0x07, "7"),
        "8": nec(0x16, 0x08, "8"),
        "9": nec(0x16, 0x09, "9"),
        "dash": nec(0x16, 0x0A, "dash"),
        "enter": nec(0x16, 0x0B, "enter"),
        "red": nec(0x16, 0x70, "red"),
        "green": nec(0x16, 0x71, "green"),
        "yellow": nec(0x16, 0x72, "yellow"),
        "blue": nec(0x16, 0x73, "blue"),
    },
)
register_profile(DIRECTV_IR)

DIRECTV_NETWORK = DeviceProfile(
    id="directv_network",
    name="DirecTV (Network)",
    brand="DirecTV",
    category="cable",
    model_years="2015+",
    description="DirecTV Genie network control.",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("directv", ""),
    network_port=8080,
    network_protocol="http",
    network_commands={
        "get_locations": NetworkCommand("get_locations", "GET", "/info/getLocations", {}),
        "tune_channel": NetworkCommand("tune_channel", "GET", "/tv/tune?major={channel}", {}),
        "key_power": NetworkCommand("key_power", "GET", "/remote/processKey?key=power", {}),
        "key_guide": NetworkCommand("key_guide", "GET", "/remote/processKey?key=guide", {}),
        "key_menu": NetworkCommand("key_menu", "GET", "/remote/processKey?key=menu", {}),
        "key_up": NetworkCommand("key_up", "GET", "/remote/processKey?key=up", {}),
        "key_down": NetworkCommand("key_down", "GET", "/remote/processKey?key=down", {}),
        "key_left": NetworkCommand("key_left", "GET", "/remote/processKey?key=left", {}),
        "key_right": NetworkCommand("key_right", "GET", "/remote/processKey?key=right", {}),
        "key_select": NetworkCommand("key_select", "GET", "/remote/processKey?key=select", {}),
        "key_exit": NetworkCommand("key_exit", "GET", "/remote/processKey?key=exit", {}),
        "key_play": NetworkCommand("key_play", "GET", "/remote/processKey?key=play", {}),
        "key_pause": NetworkCommand("key_pause", "GET", "/remote/processKey?key=pause", {}),
        "key_rew": NetworkCommand("key_rew", "GET", "/remote/processKey?key=rew", {}),
        "key_ffwd": NetworkCommand("key_ffwd", "GET", "/remote/processKey?key=ffwd", {}),
        "key_record": NetworkCommand("key_record", "GET", "/remote/processKey?key=record", {}),
    },
)
register_profile(DIRECTV_NETWORK)
