"""TiVo profiles."""

TIVO_IR = DeviceProfile(
    id="tivo_ir",
    name="TiVo (IR)",
    brand="TiVo",
    category="cable",
    model_years="2010+",
    description="TiVo DVRs and Stream devices.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("tivo", ""),
    ir_codes={
        "tivo": nec(0x20, 0xE4, "tivo"),
        "live_tv": nec(0x20, 0xE5, "live_tv"),
        "guide": nec(0x20, 0xE6, "guide"),
        "info": nec(0x20, 0xE7, "info"),
        "up": nec(0x20, 0xE8, "up"),
        "down": nec(0x20, 0xE9, "down"),
        "left": nec(0x20, 0xEA, "left"),
        "right": nec(0x20, 0xEB, "right"),
        "select": nec(0x20, 0xEC, "select"),
        "ch_up": nec(0x20, 0xED, "ch_up"),
        "ch_down": nec(0x20, 0xEE, "ch_down"),
        "thumbs_up": nec(0x20, 0xEF, "thumbs_up"),
        "thumbs_down": nec(0x20, 0xF0, "thumbs_down"),
        "play": nec(0x20, 0xF1, "play"),
        "pause": nec(0x20, 0xF2, "pause"),
        "slow": nec(0x20, 0xF3, "slow"),
        "rewind": nec(0x20, 0xF4, "rewind"),
        "fast_forward": nec(0x20, 0xF5, "fast_forward"),
        "record": nec(0x20, 0xF6, "record"),
        "skip_back": nec(0x20, 0xF7, "skip_back"),
        "skip_forward": nec(0x20, 0xF8, "skip_forward"),
        "0": nec(0x20, 0x00, "0"),
        "1": nec(0x20, 0x01, "1"),
        "2": nec(0x20, 0x02, "2"),
        "3": nec(0x20, 0x03, "3"),
        "4": nec(0x20, 0x04, "4"),
        "5": nec(0x20, 0x05, "5"),
        "6": nec(0x20, 0x06, "6"),
        "7": nec(0x20, 0x07, "7"),
        "8": nec(0x20, 0x08, "8"),
        "9": nec(0x20, 0x09, "9"),
        "clear": nec(0x20, 0x0A, "clear"),
        "enter": nec(0x20, 0x0B, "enter"),
        "zoom": nec(0x20, 0xF9, "zoom"),
        "a_yellow": nec(0x20, 0xFA, "a_yellow"),
        "b_blue": nec(0x20, 0xFB, "b_blue"),
        "c_red": nec(0x20, 0xFC, "c_red"),
        "d_green": nec(0x20, 0xFD, "d_green"),
    },
)
register_profile(TIVO_IR)

TIVO_NETWORK = DeviceProfile(
    id="tivo_network",
    name="TiVo (Network)",
    brand="TiVo",
    category="cable",
    model_years="2012+",
    description="TiVo network control protocol.",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("tivo", ""),
    network_port=31339,
    network_protocol="tcp",
    network_commands={
        "tivo": NetworkCommand("tivo", "RAW", "IRCODE TIVO\r\n", {}),
        "guide": NetworkCommand("guide", "RAW", "IRCODE GUIDE\r\n", {}),
        "up": NetworkCommand("up", "RAW", "IRCODE UP\r\n", {}),
        "down": NetworkCommand("down", "RAW", "IRCODE DOWN\r\n", {}),
        "left": NetworkCommand("left", "RAW", "IRCODE LEFT\r\n", {}),
        "right": NetworkCommand("right", "RAW", "IRCODE RIGHT\r\n", {}),
        "select": NetworkCommand("select", "RAW", "IRCODE SELECT\r\n", {}),
        "ch_up": NetworkCommand("ch_up", "RAW", "IRCODE CHANNELUP\r\n", {}),
        "ch_down": NetworkCommand("ch_down", "RAW", "IRCODE CHANNELDOWN\r\n", {}),
        "play": NetworkCommand("play", "RAW", "IRCODE PLAY\r\n", {}),
        "pause": NetworkCommand("pause", "RAW", "IRCODE PAUSE\r\n", {}),
        "rewind": NetworkCommand("rewind", "RAW", "IRCODE REVERSE\r\n", {}),
        "fast_forward": NetworkCommand("fast_forward", "RAW", "IRCODE FORWARD\r\n", {}),
        "record": NetworkCommand("record", "RAW", "IRCODE RECORD\r\n", {}),
        "tune_channel": NetworkCommand("tune_channel", "RAW", "SETCH {channel}\r\n", {}),
    },
)
register_profile(TIVO_NETWORK)
