"""Samsung Blu-ray profiles."""

SAMSUNG_BLURAY = DeviceProfile(
    id="samsung_bluray",
    name="Samsung Blu-ray Player",
    brand="Samsung",
    category="bluray",
    model_years="2015+",
    description="Samsung UBD series 4K Blu-ray players.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("samsung", ""),
    ir_codes={
        "power": samsung(0x0C, 0x0C, "power"),
        "eject": samsung(0x0C, 0x1D, "eject"),
        "play": samsung(0x0C, 0x47, "play"),
        "pause": samsung(0x0C, 0x4A, "pause"),
        "stop": samsung(0x0C, 0x46, "stop"),
        "rewind": samsung(0x0C, 0x45, "rewind"),
        "fast_forward": samsung(0x0C, 0x48, "fast_forward"),
        "prev_chapter": samsung(0x0C, 0x55, "prev_chapter"),
        "next_chapter": samsung(0x0C, 0x4F, "next_chapter"),
        "menu": samsung(0x0C, 0x60, "menu"),
        "popup_menu": samsung(0x0C, 0x67, "popup_menu"),
        "home": samsung(0x0C, 0x79, "home"),
        "up": samsung(0x0C, 0x60, "up"),
        "down": samsung(0x0C, 0x61, "down"),
        "left": samsung(0x0C, 0x65, "left"),
        "right": samsung(0x0C, 0x62, "right"),
        "enter": samsung(0x0C, 0x68, "enter"),
        "return": samsung(0x0C, 0x58, "return"),
        "info": samsung(0x0C, 0x1F, "info"),
        "audio": samsung(0x0C, 0x4B, "audio"),
        "subtitle": samsung(0x0C, 0x4C, "subtitle"),
        "red": samsung(0x0C, 0x6C, "red"),
        "green": samsung(0x0C, 0x14, "green"),
        "yellow": samsung(0x0C, 0x15, "yellow"),
        "blue": samsung(0x0C, 0x16, "blue"),
        "0": samsung(0x0C, 0x11, "0"),
        "1": samsung(0x0C, 0x04, "1"),
        "2": samsung(0x0C, 0x05, "2"),
        "3": samsung(0x0C, 0x06, "3"),
        "4": samsung(0x0C, 0x08, "4"),
        "5": samsung(0x0C, 0x09, "5"),
        "6": samsung(0x0C, 0x0A, "6"),
        "7": samsung(0x0C, 0x0C, "7"),
        "8": samsung(0x0C, 0x0D, "8"),
        "9": samsung(0x0C, 0x0E, "9"),
    },
)
register_profile(SAMSUNG_BLURAY)
