"""Sonos Soundbar profiles - Network only."""

SONOS_SOUNDBAR = DeviceProfile(
    id="sonos_soundbar",
    name="Sonos Soundbar (Network)",
    brand="Sonos",
    category="soundbar",
    model_years="2016+",
    description="Sonos soundbars (Arc, Beam, Playbar, Playbase). Network control via UPnP.",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("sonos", ""),
    network_port=1400,
    network_protocol="http",
    network_commands={
        "play": NetworkCommand("play", "POST", "/MediaRenderer/AVTransport/Control", 
            {"action": "Play", "InstanceID": 0, "Speed": 1}),
        "pause": NetworkCommand("pause", "POST", "/MediaRenderer/AVTransport/Control",
            {"action": "Pause", "InstanceID": 0}),
        "stop": NetworkCommand("stop", "POST", "/MediaRenderer/AVTransport/Control",
            {"action": "Stop", "InstanceID": 0}),
        "next": NetworkCommand("next", "POST", "/MediaRenderer/AVTransport/Control",
            {"action": "Next", "InstanceID": 0}),
        "previous": NetworkCommand("previous", "POST", "/MediaRenderer/AVTransport/Control",
            {"action": "Previous", "InstanceID": 0}),
        "vol_set": NetworkCommand("vol_set", "POST", "/MediaRenderer/RenderingControl/Control",
            {"action": "SetVolume", "InstanceID": 0, "Channel": "Master", "DesiredVolume": 50}),
        "mute_on": NetworkCommand("mute_on", "POST", "/MediaRenderer/RenderingControl/Control",
            {"action": "SetMute", "InstanceID": 0, "Channel": "Master", "DesiredMute": 1}),
        "mute_off": NetworkCommand("mute_off", "POST", "/MediaRenderer/RenderingControl/Control",
            {"action": "SetMute", "InstanceID": 0, "Channel": "Master", "DesiredMute": 0}),
        "get_volume": NetworkCommand("get_volume", "POST", "/MediaRenderer/RenderingControl/Control",
            {"action": "GetVolume", "InstanceID": 0, "Channel": "Master"}),
        "night_mode_on": NetworkCommand("night_mode_on", "POST", "/MediaRenderer/RenderingControl/Control",
            {"action": "SetEQ", "InstanceID": 0, "EQType": "NightMode", "DesiredValue": 1}),
        "night_mode_off": NetworkCommand("night_mode_off", "POST", "/MediaRenderer/RenderingControl/Control",
            {"action": "SetEQ", "InstanceID": 0, "EQType": "NightMode", "DesiredValue": 0}),
        "dialog_up": NetworkCommand("dialog_up", "POST", "/MediaRenderer/RenderingControl/Control",
            {"action": "SetEQ", "InstanceID": 0, "EQType": "DialogLevel", "DesiredValue": "+1"}),
    },
)
register_profile(SONOS_SOUNDBAR)
