"""BenQ Projector profiles."""

BENQ_PROJECTOR_IR = DeviceProfile(
    id="benq_projector_ir",
    name="BenQ Projector (IR)",
    brand="BenQ",
    category="projector",
    model_years="2015+",
    description="BenQ Home Theater and Gaming projectors.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("benq", ""),
    ir_codes={
        "power": nec(0x30, 0xC0, "power"),
        "power_on": nec(0x30, 0xC1, "power_on"),
        "power_off": nec(0x30, 0xC2, "power_off"),
        "input_hdmi1": nec(0x30, 0xC3, "input_hdmi1"),
        "input_hdmi2": nec(0x30, 0xC4, "input_hdmi2"),
        "input_vga": nec(0x30, 0xC5, "input_vga"),
        "input_video": nec(0x30, 0xC6, "input_video"),
        "input_svideo": nec(0x30, 0xC7, "input_svideo"),
        "menu": nec(0x30, 0xD0, "menu"),
        "up": nec(0x30, 0xD1, "up"),
        "down": nec(0x30, 0xD2, "down"),
        "left": nec(0x30, 0xD3, "left"),
        "right": nec(0x30, 0xD4, "right"),
        "enter": nec(0x30, 0xD5, "enter"),
        "back": nec(0x30, 0xD6, "back"),
        "blank": nec(0x30, 0xE0, "blank"),
        "freeze": nec(0x30, 0xE1, "freeze"),
        "aspect": nec(0x30, 0xE2, "aspect"),
        "3d_mode": nec(0x30, 0xE3, "3d_mode"),
        "picture_mode": nec(0x30, 0xE4, "picture_mode"),
        "zoom_in": nec(0x30, 0xE5, "zoom_in"),
        "zoom_out": nec(0x30, 0xE6, "zoom_out"),
        "keystone_plus": nec(0x30, 0xE7, "keystone_plus"),
        "keystone_minus": nec(0x30, 0xE8, "keystone_minus"),
        "vol_up": nec(0x30, 0xF0, "vol_up"),
        "vol_down": nec(0x30, 0xF1, "vol_down"),
        "mute": nec(0x30, 0xF2, "mute"),
        "eco_mode": nec(0x30, 0xF3, "eco_mode"),
    },
)
register_profile(BENQ_PROJECTOR_IR)

BENQ_PROJECTOR_NETWORK = DeviceProfile(
    id="benq_projector_network",
    name="BenQ Projector (Network)",
    brand="BenQ",
    category="projector",
    model_years="2018+",
    description="BenQ RS-232 over network (port 4352).",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("benq", ""),
    network_port=4352,
    network_protocol="tcp",
    network_commands={
        "power_on": NetworkCommand("power_on", "RAW", "\r*pow=on#\r", {}),
        "power_off": NetworkCommand("power_off", "RAW", "\r*pow=off#\r", {}),
        "power_query": NetworkCommand("power_query", "RAW", "\r*pow=?#\r", {}),
        "input_hdmi1": NetworkCommand("input_hdmi1", "RAW", "\r*sour=hdmi#\r", {}),
        "input_hdmi2": NetworkCommand("input_hdmi2", "RAW", "\r*sour=hdmi2#\r", {}),
        "input_vga": NetworkCommand("input_vga", "RAW", "\r*sour=RGB#\r", {}),
        "input_video": NetworkCommand("input_video", "RAW", "\r*sour=vid#\r", {}),
        "blank_on": NetworkCommand("blank_on", "RAW", "\r*blank=on#\r", {}),
        "blank_off": NetworkCommand("blank_off", "RAW", "\r*blank=off#\r", {}),
        "vol_up": NetworkCommand("vol_up", "RAW", "\r*vol=+#\r", {}),
        "vol_down": NetworkCommand("vol_down", "RAW", "\r*vol=-#\r", {}),
        "mute_on": NetworkCommand("mute_on", "RAW", "\r*mute=on#\r", {}),
        "mute_off": NetworkCommand("mute_off", "RAW", "\r*mute=off#\r", {}),
        "aspect_4_3": NetworkCommand("aspect_4_3", "RAW", "\r*asp=4:3#\r", {}),
        "aspect_16_9": NetworkCommand("aspect_16_9", "RAW", "\r*asp=16:9#\r", {}),
        "aspect_auto": NetworkCommand("aspect_auto", "RAW", "\r*asp=auto#\r", {}),
        "picture_bright": NetworkCommand("picture_bright", "RAW", "\r*appmod=bright#\r", {}),
        "picture_cinema": NetworkCommand("picture_cinema", "RAW", "\r*appmod=cine#\r", {}),
        "picture_game": NetworkCommand("picture_game", "RAW", "\r*appmod=game#\r", {}),
        "eco_on": NetworkCommand("eco_on", "RAW", "\r*lampm=eco#\r", {}),
        "eco_off": NetworkCommand("eco_off", "RAW", "\r*lampm=lnor#\r", {}),
        "lamp_hours": NetworkCommand("lamp_hours", "RAW", "\r*ltim=?#\r", {}),
    },
)
register_profile(BENQ_PROJECTOR_NETWORK)
