"""Epson Projector profiles."""

EPSON_PROJECTOR_IR = DeviceProfile(
    id="epson_projector_ir",
    name="Epson Projector (IR)",
    brand="Epson",
    category="projector",
    model_years="2015+",
    description="Epson Home Cinema and Pro projectors.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("epson", ""),
    ir_codes={
        "power": nec(0x75, 0x00, "power"),
        "power_on": nec(0x75, 0x00, "power_on"),
        "power_off": nec(0x75, 0x01, "power_off"),
        "input_hdmi1": nec(0x75, 0x04, "input_hdmi1"),
        "input_hdmi2": nec(0x75, 0x05, "input_hdmi2"),
        "input_video": nec(0x75, 0x06, "input_video"),
        "input_usb": nec(0x75, 0x07, "input_usb"),
        "input_pc": nec(0x75, 0x08, "input_pc"),
        "menu": nec(0x75, 0x10, "menu"),
        "up": nec(0x75, 0x11, "up"),
        "down": nec(0x75, 0x12, "down"),
        "left": nec(0x75, 0x13, "left"),
        "right": nec(0x75, 0x14, "right"),
        "enter": nec(0x75, 0x15, "enter"),
        "escape": nec(0x75, 0x16, "escape"),
        "blank": nec(0x75, 0x20, "blank"),
        "freeze": nec(0x75, 0x21, "freeze"),
        "aspect": nec(0x75, 0x22, "aspect"),
        "color_mode": nec(0x75, 0x23, "color_mode"),
        "lens_shift_up": nec(0x75, 0x30, "lens_shift_up"),
        "lens_shift_down": nec(0x75, 0x31, "lens_shift_down"),
        "lens_shift_left": nec(0x75, 0x32, "lens_shift_left"),
        "lens_shift_right": nec(0x75, 0x33, "lens_shift_right"),
        "zoom_in": nec(0x75, 0x34, "zoom_in"),
        "zoom_out": nec(0x75, 0x35, "zoom_out"),
        "focus_near": nec(0x75, 0x36, "focus_near"),
        "focus_far": nec(0x75, 0x37, "focus_far"),
        "keystone_up": nec(0x75, 0x40, "keystone_up"),
        "keystone_down": nec(0x75, 0x41, "keystone_down"),
        "auto_adjust": nec(0x75, 0x42, "auto_adjust"),
        "vol_up": nec(0x75, 0x50, "vol_up"),
        "vol_down": nec(0x75, 0x51, "vol_down"),
        "mute": nec(0x75, 0x52, "mute"),
    },
)
register_profile(EPSON_PROJECTOR_IR)

EPSON_PROJECTOR_NETWORK = DeviceProfile(
    id="epson_projector_network",
    name="Epson Projector (Network)",
    brand="Epson",
    category="projector",
    model_years="2015+",
    description="Epson network control via ESC/VP21.",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("epson", ""),
    network_port=3629,
    network_protocol="tcp",
    network_commands={
        "power_on": NetworkCommand("power_on", "RAW", "PWR ON\r", {}),
        "power_off": NetworkCommand("power_off", "RAW", "PWR OFF\r", {}),
        "power_query": NetworkCommand("power_query", "RAW", "PWR?\r", {}),
        "input_hdmi1": NetworkCommand("input_hdmi1", "RAW", "SOURCE 30\r", {}),
        "input_hdmi2": NetworkCommand("input_hdmi2", "RAW", "SOURCE A0\r", {}),
        "input_pc": NetworkCommand("input_pc", "RAW", "SOURCE 10\r", {}),
        "input_video": NetworkCommand("input_video", "RAW", "SOURCE 40\r", {}),
        "blank_on": NetworkCommand("blank_on", "RAW", "MUTE ON\r", {}),
        "blank_off": NetworkCommand("blank_off", "RAW", "MUTE OFF\r", {}),
        "vol_up": NetworkCommand("vol_up", "RAW", "VOL UP\r", {}),
        "vol_down": NetworkCommand("vol_down", "RAW", "VOL DOWN\r", {}),
        "aspect_normal": NetworkCommand("aspect_normal", "RAW", "ASPECT 00\r", {}),
        "aspect_169": NetworkCommand("aspect_169", "RAW", "ASPECT 30\r", {}),
        "aspect_zoom": NetworkCommand("aspect_zoom", "RAW", "ASPECT 40\r", {}),
        "color_mode_dynamic": NetworkCommand("color_mode_dynamic", "RAW", "CMODE 06\r", {}),
        "color_mode_natural": NetworkCommand("color_mode_natural", "RAW", "CMODE 07\r", {}),
        "color_mode_cinema": NetworkCommand("color_mode_cinema", "RAW", "CMODE 15\r", {}),
        "lamp_hours": NetworkCommand("lamp_hours", "RAW", "LAMP?\r", {}),
    },
)
register_profile(EPSON_PROJECTOR_NETWORK)
