"""JVC Projector profiles."""

JVC_PROJECTOR_IR = DeviceProfile(
    id="jvc_projector_ir",
    name="JVC Projector (IR)",
    brand="JVC",
    category="projector",
    model_years="2015+",
    description="JVC D-ILA projectors.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("jvc", ""),
    ir_codes={
        "power": nec(0x70, 0x02, "power"),
        "power_on": nec(0x70, 0x02, "power_on"),
        "power_off": nec(0x70, 0x03, "power_off"),
        "input_hdmi1": nec(0x70, 0x70, "input_hdmi1"),
        "input_hdmi2": nec(0x70, 0x71, "input_hdmi2"),
        "menu": nec(0x70, 0x2E, "menu"),
        "up": nec(0x70, 0x01, "up"),
        "down": nec(0x70, 0x02, "down"),
        "left": nec(0x70, 0x03, "left"),
        "right": nec(0x70, 0x04, "right"),
        "ok": nec(0x70, 0x05, "ok"),
        "back": nec(0x70, 0x06, "back"),
        "info": nec(0x70, 0x74, "info"),
        "hide": nec(0x70, 0x1D, "hide"),
        "lens_control": nec(0x70, 0x30, "lens_control"),
        "lens_shift": nec(0x70, 0x31, "lens_shift"),
        "lens_zoom": nec(0x70, 0x32, "lens_zoom"),
        "lens_focus": nec(0x70, 0x33, "lens_focus"),
        "picture_mode": nec(0x70, 0x40, "picture_mode"),
        "cmd": nec(0x70, 0x41, "cmd"),
        "aspect": nec(0x70, 0x20, "aspect"),
        "mpc": nec(0x70, 0x42, "mpc"),
        "gamma": nec(0x70, 0x43, "gamma"),
        "color_temp": nec(0x70, 0x44, "color_temp"),
        "lens_memory_1": nec(0x70, 0x90, "lens_memory_1"),
        "lens_memory_2": nec(0x70, 0x91, "lens_memory_2"),
        "lens_memory_3": nec(0x70, 0x92, "lens_memory_3"),
    },
)
register_profile(JVC_PROJECTOR_IR)

JVC_PROJECTOR_NETWORK = DeviceProfile(
    id="jvc_projector_network",
    name="JVC Projector (Network)",
    brand="JVC",
    category="projector",
    model_years="2015+",
    description="JVC network control.",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("jvc", ""),
    network_port=20554,
    network_protocol="tcp",
    network_commands={
        "power_on": NetworkCommand("power_on", "RAW", "PW1\n", {}),
        "power_off": NetworkCommand("power_off", "RAW", "PW0\n", {}),
        "power_query": NetworkCommand("power_query", "RAW", "PW\n", {}),
        "input_hdmi1": NetworkCommand("input_hdmi1", "RAW", "IP6\n", {}),
        "input_hdmi2": NetworkCommand("input_hdmi2", "RAW", "IP7\n", {}),
        "picture_film": NetworkCommand("picture_film", "RAW", "PMPM01\n", {}),
        "picture_cinema": NetworkCommand("picture_cinema", "RAW", "PMPM02\n", {}),
        "picture_natural": NetworkCommand("picture_natural", "RAW", "PMPM03\n", {}),
        "picture_hdr": NetworkCommand("picture_hdr", "RAW", "PMPM04\n", {}),
        "lens_memory_1": NetworkCommand("lens_memory_1", "RAW", "INML0\n", {}),
        "lens_memory_2": NetworkCommand("lens_memory_2", "RAW", "INML1\n", {}),
        "lens_memory_3": NetworkCommand("lens_memory_3", "RAW", "INML2\n", {}),
        "aspect_zoom": NetworkCommand("aspect_zoom", "RAW", "ISAS0\n", {}),
        "aspect_auto": NetworkCommand("aspect_auto", "RAW", "ISAS1\n", {}),
        "aspect_native": NetworkCommand("aspect_native", "RAW", "ISAS2\n", {}),
    },
)
register_profile(JVC_PROJECTOR_NETWORK)
