"""Optoma Projector profiles."""

OPTOMA_PROJECTOR_IR = DeviceProfile(
    id="optoma_projector_ir",
    name="Optoma Projector (IR)",
    brand="Optoma",
    category="projector",
    model_years="2015+",
    description="Optoma UHD and HD projectors.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("optoma", ""),
    ir_codes={
        "power": nec(0x87, 0x00, "power"),
        "power_on": nec(0x87, 0x01, "power_on"),
        "power_off": nec(0x87, 0x02, "power_off"),
        "input_hdmi1": nec(0x87, 0x10, "input_hdmi1"),
        "input_hdmi2": nec(0x87, 0x11, "input_hdmi2"),
        "input_hdmi3": nec(0x87, 0x12, "input_hdmi3"),
        "input_vga": nec(0x87, 0x13, "input_vga"),
        "menu": nec(0x87, 0x20, "menu"),
        "up": nec(0x87, 0x21, "up"),
        "down": nec(0x87, 0x22, "down"),
        "left": nec(0x87, 0x23, "left"),
        "right": nec(0x87, 0x24, "right"),
        "enter": nec(0x87, 0x25, "enter"),
        "resync": nec(0x87, 0x26, "resync"),
        "blank": nec(0x87, 0x30, "blank"),
        "freeze": nec(0x87, 0x31, "freeze"),
        "zoom_in": nec(0x87, 0x32, "zoom_in"),
        "zoom_out": nec(0x87, 0x33, "zoom_out"),
        "aspect": nec(0x87, 0x34, "aspect"),
        "picture_mode": nec(0x87, 0x35, "picture_mode"),
        "keystone_plus": nec(0x87, 0x40, "keystone_plus"),
        "keystone_minus": nec(0x87, 0x41, "keystone_minus"),
        "vol_up": nec(0x87, 0x50, "vol_up"),
        "vol_down": nec(0x87, 0x51, "vol_down"),
        "mute": nec(0x87, 0x52, "mute"),
    },
)
register_profile(OPTOMA_PROJECTOR_IR)

OPTOMA_PROJECTOR_NETWORK = DeviceProfile(
    id="optoma_projector_network",
    name="Optoma Projector (Network)",
    brand="Optoma",
    category="projector",
    model_years="2018+",
    description="Optoma network control.",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("optoma", ""),
    network_port=23,
    network_protocol="telnet",
    network_commands={
        "power_on": NetworkCommand("power_on", "RAW", "~0000 1\r", {}),
        "power_off": NetworkCommand("power_off", "RAW", "~0000 0\r", {}),
        "power_query": NetworkCommand("power_query", "RAW", "~00124 1\r", {}),
        "input_hdmi1": NetworkCommand("input_hdmi1", "RAW", "~0012 15\r", {}),
        "input_hdmi2": NetworkCommand("input_hdmi2", "RAW", "~0012 18\r", {}),
        "input_vga": NetworkCommand("input_vga", "RAW", "~0012 5\r", {}),
        "blank_on": NetworkCommand("blank_on", "RAW", "~0049 1\r", {}),
        "blank_off": NetworkCommand("blank_off", "RAW", "~0049 0\r", {}),
        "vol_set": NetworkCommand("vol_set", "RAW", "~0089 10\r", {}),
        "mute_on": NetworkCommand("mute_on", "RAW", "~0060 1\r", {}),
        "mute_off": NetworkCommand("mute_off", "RAW", "~0060 0\r", {}),
    },
)
register_profile(OPTOMA_PROJECTOR_NETWORK)
