"""Hisense TV profiles."""

HISENSE_TV_IR = DeviceProfile(
    id="hisense_tv_ir",
    name="Hisense TV (IR)",
    brand="Hisense",
    category="tv",
    model_years="2015+",
    description="Hisense Smart TVs using NEC protocol.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("hisense", ""),
    ir_codes={
        "power": nec(0x04, 0x08, "power"),
        "vol_up": nec(0x04, 0x02, "vol_up"),
        "vol_down": nec(0x04, 0x03, "vol_down"),
        "mute": nec(0x04, 0x09, "mute"),
        "ch_up": nec(0x04, 0x00, "ch_up"),
        "ch_down": nec(0x04, 0x01, "ch_down"),
        "input": nec(0x04, 0x0B, "input"),
        "menu": nec(0x04, 0x43, "menu"),
        "home": nec(0x04, 0x7C, "home"),
        "back": nec(0x04, 0x28, "back"),
        "exit": nec(0x04, 0x5B, "exit"),
        "up": nec(0x04, 0x40, "up"),
        "down": nec(0x04, 0x41, "down"),
        "left": nec(0x04, 0x07, "left"),
        "right": nec(0x04, 0x06, "right"),
        "enter": nec(0x04, 0x44, "enter"),
        "0": nec(0x04, 0x10, "0"),
        "1": nec(0x04, 0x11, "1"),
        "2": nec(0x04, 0x12, "2"),
        "3": nec(0x04, 0x13, "3"),
        "4": nec(0x04, 0x14, "4"),
        "5": nec(0x04, 0x15, "5"),
        "6": nec(0x04, 0x16, "6"),
        "7": nec(0x04, 0x17, "7"),
        "8": nec(0x04, 0x18, "8"),
        "9": nec(0x04, 0x19, "9"),
        "netflix": nec(0x04, 0x67, "netflix"),
        "youtube": nec(0x04, 0x68, "youtube"),
        "prime": nec(0x04, 0x69, "prime"),
    },
)
register_profile(HISENSE_TV_IR)

# Hisense Roku TV uses same codes as TCL Roku
HISENSE_ROKU_TV = DeviceProfile(
    id="hisense_roku_tv",
    name="Hisense Roku TV (IR)",
    brand="Hisense",
    category="tv",
    model_years="2018+",
    description="Hisense Roku TVs - uses Roku IR codes.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("hisense", ""),
    ir_codes={
        "power": nec(0xEE, 0x8D, "power"),
        "vol_up": nec(0xEE, 0x84, "vol_up"),
        "vol_down": nec(0xEE, 0x85, "vol_down"),
        "mute": nec(0xEE, 0x8C, "mute"),
        "home": nec(0xEE, 0x8E, "home"),
        "back": nec(0xEE, 0x83, "back"),
        "up": nec(0xEE, 0x9A, "up"),
        "down": nec(0xEE, 0x9B, "down"),
        "left": nec(0xEE, 0x9C, "left"),
        "right": nec(0xEE, 0x9D, "right"),
        "enter": nec(0xEE, 0x9E, "enter"),
        "play": nec(0xEE, 0x8F, "play"),
        "pause": nec(0xEE, 0x8F, "pause"),
        "rewind": nec(0xEE, 0x8B, "rewind"),
        "fast_forward": nec(0xEE, 0x8A, "fast_forward"),
    },
)
register_profile(HISENSE_ROKU_TV)
