"""Daikin AC profiles."""

DAIKIN_AC_NETWORK = DeviceProfile(
    id="daikin_ac_network",
    name="Daikin AC (Network/WiFi)",
    brand="Daikin",
    category="ac",
    model_years="2018+",
    description="Daikin WiFi enabled AC units with BRP072C adapter.",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("daikin", ""),
    network_port=80,
    network_protocol="http",
    network_commands={
        "get_info": NetworkCommand("get_info", "GET", "/aircon/get_control_info", {}),
        "get_sensor": NetworkCommand("get_sensor", "GET", "/aircon/get_sensor_info", {}),
        "power_on": NetworkCommand("power_on", "GET", "/aircon/set_control_info?pow=1", {}),
        "power_off": NetworkCommand("power_off", "GET", "/aircon/set_control_info?pow=0", {}),
        "mode_cool": NetworkCommand("mode_cool", "GET", "/aircon/set_control_info?mode=3", {}),
        "mode_heat": NetworkCommand("mode_heat", "GET", "/aircon/set_control_info?mode=4", {}),
        "mode_auto": NetworkCommand("mode_auto", "GET", "/aircon/set_control_info?mode=0", {}),
        "mode_dry": NetworkCommand("mode_dry", "GET", "/aircon/set_control_info?mode=2", {}),
        "mode_fan": NetworkCommand("mode_fan", "GET", "/aircon/set_control_info?mode=6", {}),
        "temp_20": NetworkCommand("temp_20", "GET", "/aircon/set_control_info?stemp=20.0", {}),
        "temp_22": NetworkCommand("temp_22", "GET", "/aircon/set_control_info?stemp=22.0", {}),
        "temp_24": NetworkCommand("temp_24", "GET", "/aircon/set_control_info?stemp=24.0", {}),
        "temp_26": NetworkCommand("temp_26", "GET", "/aircon/set_control_info?stemp=26.0", {}),
        "fan_auto": NetworkCommand("fan_auto", "GET", "/aircon/set_control_info?f_rate=A", {}),
        "fan_quiet": NetworkCommand("fan_quiet", "GET", "/aircon/set_control_info?f_rate=B", {}),
        "fan_1": NetworkCommand("fan_1", "GET", "/aircon/set_control_info?f_rate=3", {}),
        "fan_2": NetworkCommand("fan_2", "GET", "/aircon/set_control_info?f_rate=4", {}),
        "fan_3": NetworkCommand("fan_3", "GET", "/aircon/set_control_info?f_rate=5", {}),
        "fan_4": NetworkCommand("fan_4", "GET", "/aircon/set_control_info?f_rate=6", {}),
        "fan_5": NetworkCommand("fan_5", "GET", "/aircon/set_control_info?f_rate=7", {}),
        "swing_on": NetworkCommand("swing_on", "GET", "/aircon/set_control_info?f_dir=3", {}),
        "swing_off": NetworkCommand("swing_off", "GET", "/aircon/set_control_info?f_dir=0", {}),
    },
)
register_profile(DAIKIN_AC_NETWORK)
