"""Marantz AVR profiles - Uses similar protocol to Denon."""

MARANTZ_AVR_IR = DeviceProfile(
    id="marantz_avr_ir",
    name="Marantz AVR (IR)",
    brand="Marantz",
    category="receiver",
    model_years="2010+",
    description="Marantz AV Receivers - IR control.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("marantz", ""),
    ir_codes={
        "power": nec(0x40, 0x1C, "power"),
        "power_on": nec(0x40, 0x1C, "power_on"),
        "power_off": nec(0x40, 0x1D, "power_off"),
        "vol_up": nec(0x40, 0x1A, "vol_up"),
        "vol_down": nec(0x40, 0x1B, "vol_down"),
        "mute": nec(0x40, 0x38, "mute"),
        "input_cd": nec(0x40, 0x14, "input_cd"),
        "input_tuner": nec(0x40, 0x15, "input_tuner"),
        "input_aux1": nec(0x40, 0x16, "input_aux1"),
        "input_aux2": nec(0x40, 0x17, "input_aux2"),
        "input_dvd": nec(0x40, 0x18, "input_dvd"),
        "input_vcr": nec(0x40, 0x0F, "input_vcr"),
        "input_tv": nec(0x40, 0x10, "input_tv"),
        "menu": nec(0x40, 0x54, "menu"),
        "up": nec(0x40, 0x52, "up"),
        "down": nec(0x40, 0x53, "down"),
        "left": nec(0x40, 0x50, "left"),
        "right": nec(0x40, 0x51, "right"),
        "enter": nec(0x40, 0x40, "enter"),
    },
)
register_profile(MARANTZ_AVR_IR)

# Marantz Network (same as Denon Telnet protocol)
MARANTZ_AVR_NETWORK = DeviceProfile(
    id="marantz_avr_network",
    name="Marantz AVR (Network)",
    brand="Marantz",
    category="receiver",
    model_years="2012+",
    description="Marantz network control via Telnet (same as Denon protocol).",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("marantz", ""),
    network_port=23,
    network_protocol="telnet",
    network_commands={
        "power_on": NetworkCommand("power_on", "RAW", "PWON\r", {}),
        "power_off": NetworkCommand("power_off", "RAW", "PWSTANDBY\r", {}),
        "vol_up": NetworkCommand("vol_up", "RAW", "MVUP\r", {}),
        "vol_down": NetworkCommand("vol_down", "RAW", "MVDOWN\r", {}),
        "mute_on": NetworkCommand("mute_on", "RAW", "MUON\r", {}),
        "mute_off": NetworkCommand("mute_off", "RAW", "MUOFF\r", {}),
        "input_cd": NetworkCommand("input_cd", "RAW", "SICD\r", {}),
        "input_dvd": NetworkCommand("input_dvd", "RAW", "SIDVD\r", {}),
        "input_bd": NetworkCommand("input_bd", "RAW", "SIBD\r", {}),
        "input_tv": NetworkCommand("input_tv", "RAW", "SITV\r", {}),
        "input_sat_cbl": NetworkCommand("input_sat_cbl", "RAW", "SISAT/CBL\r", {}),
        "input_game": NetworkCommand("input_game", "RAW", "SIGAME\r", {}),
        "input_aux1": NetworkCommand("input_aux1", "RAW", "SIAUX1\r", {}),
        "input_aux2": NetworkCommand("input_aux2", "RAW", "SIAUX2\r", {}),
        "input_net": NetworkCommand("input_net", "RAW", "SINET\r", {}),
        "input_bluetooth": NetworkCommand("input_bluetooth", "RAW", "SIBT\r", {}),
        "surround_stereo": NetworkCommand("surround_stereo", "RAW", "MSSTEREO\r", {}),
        "surround_auto": NetworkCommand("surround_auto", "RAW", "MSAUTO\r", {}),
        "surround_movie": NetworkCommand("surround_movie", "RAW", "MSMOVIE\r", {}),
        "surround_music": NetworkCommand("surround_music", "RAW", "MSMUSIC\r", {}),
        "surround_pure_direct": NetworkCommand("surround_pure_direct", "RAW", "MSPURE DIRECT\r", {}),
    },
)
register_profile(MARANTZ_AVR_NETWORK)
