"""Pioneer AVR profiles."""

PIONEER_AVR_IR = DeviceProfile(
    id="pioneer_avr_ir",
    name="Pioneer AVR (IR)",
    brand="Pioneer",
    category="receiver",
    model_years="2010+",
    description="Pioneer Elite AV Receivers - IR control.",
    control_methods=[ControlMethod.IR],
    logo_url=BRAND_LOGOS.get("pioneer", ""),
    ir_codes={
        "power": nec(0xA5, 0x1C, "power"),
        "power_on": nec(0xA5, 0x1C, "power_on"),
        "power_off": nec(0xA5, 0x1D, "power_off"),
        "vol_up": nec(0xA5, 0x0A, "vol_up"),
        "vol_down": nec(0xA5, 0x0B, "vol_down"),
        "mute": nec(0xA5, 0x09, "mute"),
        "input_bd": nec(0xA5, 0x19, "input_bd"),
        "input_dvd": nec(0xA5, 0x04, "input_dvd"),
        "input_tv_sat": nec(0xA5, 0x05, "input_tv_sat"),
        "input_dvr": nec(0xA5, 0x06, "input_dvr"),
        "input_video": nec(0xA5, 0x10, "input_video"),
        "input_hdmi1": nec(0xA5, 0xD4, "input_hdmi1"),
        "input_hdmi2": nec(0xA5, 0xD5, "input_hdmi2"),
        "input_hdmi3": nec(0xA5, 0xD6, "input_hdmi3"),
        "input_hdmi4": nec(0xA5, 0xD7, "input_hdmi4"),
        "input_cd": nec(0xA5, 0x01, "input_cd"),
        "input_tuner": nec(0xA5, 0x02, "input_tuner"),
        "input_phono": nec(0xA5, 0x00, "input_phono"),
        "input_usb": nec(0xA5, 0xD0, "input_usb"),
        "input_ipod": nec(0xA5, 0xD1, "input_ipod"),
        "input_adapter": nec(0xA5, 0xD2, "input_adapter"),
        "surround_auto": nec(0xA5, 0x50, "surround_auto"),
        "surround_stereo": nec(0xA5, 0x51, "surround_stereo"),
        "surround_advanced": nec(0xA5, 0x52, "surround_advanced"),
        "menu": nec(0xA5, 0xB0, "menu"),
        "up": nec(0xA5, 0xB1, "up"),
        "down": nec(0xA5, 0xB2, "down"),
        "left": nec(0xA5, 0xB3, "left"),
        "right": nec(0xA5, 0xB4, "right"),
        "enter": nec(0xA5, 0xB5, "enter"),
        "return": nec(0xA5, 0xB6, "return"),
    },
)
register_profile(PIONEER_AVR_IR)

PIONEER_AVR_NETWORK = DeviceProfile(
    id="pioneer_avr_network",
    name="Pioneer AVR (Network)",
    brand="Pioneer",
    category="receiver",
    model_years="2012+",
    description="Pioneer network control via Telnet.",
    control_methods=[ControlMethod.NETWORK],
    logo_url=BRAND_LOGOS.get("pioneer", ""),
    network_port=23,
    network_protocol="telnet",
    network_commands={
        "power_on": NetworkCommand("power_on", "RAW", "PO\r\n", {}),
        "power_off": NetworkCommand("power_off", "RAW", "PF\r\n", {}),
        "vol_up": NetworkCommand("vol_up", "RAW", "VU\r\n", {}),
        "vol_down": NetworkCommand("vol_down", "RAW", "VD\r\n", {}),
        "mute_on": NetworkCommand("mute_on", "RAW", "MO\r\n", {}),
        "mute_off": NetworkCommand("mute_off", "RAW", "MF\r\n", {}),
        "input_bd": NetworkCommand("input_bd", "RAW", "25FN\r\n", {}),
        "input_dvd": NetworkCommand("input_dvd", "RAW", "04FN\r\n", {}),
        "input_tv_sat": NetworkCommand("input_tv_sat", "RAW", "05FN\r\n", {}),
        "input_hdmi1": NetworkCommand("input_hdmi1", "RAW", "19FN\r\n", {}),
        "input_hdmi2": NetworkCommand("input_hdmi2", "RAW", "20FN\r\n", {}),
        "input_hdmi3": NetworkCommand("input_hdmi3", "RAW", "21FN\r\n", {}),
        "input_cd": NetworkCommand("input_cd", "RAW", "01FN\r\n", {}),
        "input_usb": NetworkCommand("input_usb", "RAW", "17FN\r\n", {}),
        "input_network": NetworkCommand("input_network", "RAW", "26FN\r\n", {}),
        "input_bluetooth": NetworkCommand("input_bluetooth", "RAW", "33FN\r\n", {}),
        "listening_mode_auto": NetworkCommand("listening_mode_auto", "RAW", "0005SR\r\n", {}),
        "listening_mode_stereo": NetworkCommand("listening_mode_stereo", "RAW", "0010SR\r\n", {}),
        "listening_mode_direct": NetworkCommand("listening_mode_direct", "RAW", "0007SR\r\n", {}),
    },
)
register_profile(PIONEER_AVR_NETWORK)
